[package]
name = "opentaws"
version = "0.1.0"
authors = [
	"Wanja Zaeske <wanja.zaeske@tu-clausthal.de>",
	"Janick Beck <janick.beck@tu-clausthal.de>",
	"Umut Durak <umut.durak@tu-clausthal.de>",
	]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "An async adapter for mavlink conections"
readme = "README.md"
repository = "https://github.com/aeronautical-informatics/openTAWS"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[lib]
#crate-type = ['cdylib']

[features]
default = [ ]
capi = [ ]
wasi = [ "serde", "serde_json", "wasm-bindgen" ]

[dependencies]
lazy_static = "1"
uom = "0"

### WASI deps
serde = { version = "1.0", features = [ "derive" ], optional = true }
serde_json = { version = "1.0" , optional = true }
wasm-bindgen = { version = "0", optional = true}

### Test deps
strum = { version = "^0.19", features = ["derive"]}

[dev-dependencies]
async-trait = "^0.1.41"
cucumber = { package = "cucumber_rust", git = "https://github.com/bbqsrc/cucumber-rust", branch = "main" } # TODO revert to regular release
futures = "0"
quickcheck = "^0.9.2"
rand = "0.7"

[[test]]
name = "cucumber"
harness = false # Allows Cucumber to print output instead of libtest
path = "test/cucumber.rs"
